# Generated by Django 5.0.6 on 2026-08-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(help_text='e.g. 20320018110', max_length=50, unique=True)),
                ('branch', models.CharField(choices=[('Andheri', 'Andheri'), ('Thane', 'Thane'), ('Dadar', 'Dadar'), ('Vashi', 'Vashi')], max_length=20)),
                ('assigned_by', models.CharField(blank=True, default='', help_text='Employee who assigned the job', max_length=150)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved Pending', 'Approved Pending'), ('Approved', 'Approved'), ('Closed', 'Closed'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_date', models.DateField(help_text='Submission date')),
                ('eta', models.DateField(help_text='Submit ETA date')),
                ('approved_eta', models.DateField(blank=True, help_text='Approved ETA date', null=True)),
                ('advance_paid', models.BooleanField(default=False, help_text='Whether advance payment is paid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Sheet',
                'verbose_name_plural': 'Job Sheets',
                'ordering': ['-created_at'],
            },
        ),
    ]
