# Generated by Django 5.0.6 on 2026-08-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsheet',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ready', 'Ready'), ('Approved Pending', 'Approved Pending'), ('Approved', 'Approved'), ('Closed', 'Closed'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
