# Generated by Django 5.2.13 on 2026-08-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsheets', '0004_remove_jobsheet_repaired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsheet',
            name='advance_paid',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('NA', 'Not Applicable')], default='Unpaid', help_text='Advance payment status', max_length=10),
        ),
    ]
