# Generated by Django 5.0.6 on 2026-08-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsheets', '0005_alter_jobsheet_advance_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsheet',
            name='advance_paid',
            field=models.BooleanField(default=False, help_text='Whether advance payment is paid'),
        ),
    ]
