# Generated by Django 5.0.6 on 2026-08-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsheets', '0007_jobsheet_is_repaired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsheet',
            name='advance_paid',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('NA', 'Not Applicable')], default='Unpaid', help_text='Advance payment status: Paid, Unpaid, or NA', max_length=10),
        ),
    ]
