# Generated by Django 5.2.13 on 2026-08-14 13:11

from django.db import migrations


def fix_advance_paid_data(apps, schema_editor):
    """Fix any corrupted advance_paid values from BooleanField migration"""
    JobSheet = apps.get_model('jobsheets', 'JobSheet')
    
    for job in JobSheet.objects.all():
        # Fix numeric values that came from BooleanField storage
        if job.advance_paid == '1' or job.advance_paid == 1 or job.advance_paid is True:
            job.advance_paid = 'Paid'
            job.save()
        elif job.advance_paid == '0' or job.advance_paid == 0 or job.advance_paid is False:
            job.advance_paid = 'Unpaid'
            job.save()
        # Ensure only valid values exist
        elif job.advance_paid not in ['Paid', 'Unpaid', 'NA', None]:
            job.advance_paid = 'Unpaid'  # Default to Unpaid for unknown values
            job.save()


def reverse_fix(apps, schema_editor):
    """Reverse is not needed for data fix"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('jobsheets', '0008_alter_jobsheet_advance_paid'),
    ]

    operations = [
        migrations.RunPython(fix_advance_paid_data, reverse_fix),
    ]
