# Generated by Django 5.0.6 on 2026-08-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('branch_user', 'Branch User'), ('viewer', 'Viewer')], default='branch_user', max_length=20),
        ),
    ]
